server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true #默认就是true
    register-with-eureka: false # 是否注册服务到eureka  客户端 可不注册

#ribbon:
#  ReadTimeout: 4000 #鏈接超时时间
#  ConnectTimeout: 4000 #获取资源超时时间
feign:
  hystrix:
    enabled: true
