server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: payment-service8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/**
        - id: order-service80
          uri: lb://cloud-consumer-service
          predicates:
            - Path=/consumer/**
#            - Host=**.test.org,**.demo.org
#            - Cookie=username,test

#      discovery:
#        locator:
#          enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: gateway-service
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

