server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.115.200.114:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: zaq1@Xsw2
mybatis:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.**.domain
logging:
  level:
    com.payment.dao: debug
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    fetch-registry: true # 获取已有注册信息，默认true，单节点无所谓，集群必须为true才能配合ribbon
    register-with-eureka: true
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #把服务ip地址注册到注册中心
    prefer-ip-address: true
    hostname: paymentServer8001


